version: "3.9"
services:
  app:
    build: .
    container_name: elmarco_app
    restart: always
    user: "node"
    working_dir: /home/node/app
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/node/app
    depends_on:
      - kv
      - db
    command: "npm start"
    networks:
      - marcobotnet

  kv:
    image: quay.io/coreos/etcd:v3.2.13
    container_name: elmarco_kv
    restart: always
    env_file:
      - .kv.env
    volumes:
      - ../storage/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
    networks:
      - marcobotnet
  
  db:
    image: mongo:5.0.8
    container_name: elmarco_db
    restart: always
    env_file:
      - .db.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=elmaaarrco
      - ME_CONFIG_MONGODB_URL=mongodb://root:elmaaarrco@elmarco_db:27017
    networks:
      - marcobotnet
networks:
  marcobotnet:
    driver: bridge